services:
  server:
    container_name: mc-server
    image: minecraft:local
    build:
      dockerfile: dockerfiles/Dockerfile.${SERVER_TYPE}
      context: .
      args:
        - SERVER_VERSION=${SERVER_VERSION}
    ports:
      - 25565:25565
    volumes:
      - minecraft-world:/minecraft/world
    stop_grace_period: 5m

volumes:
  minecraft-world:
